accounts/urls.py
from django.urls import path

from .views import RegisterView

# from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
]

organizations/urls.py
from django.urls import path

from .api import get_org_data
from .views import (OrganizationCreateView, OrganizationDetailView,
                    OrganizationListView, OrganizationUpdateView)

app_name = 'organizations'

urlpatterns = [
    path('', OrganizationListView.as_view(), name='list'),
    path('create/', OrganizationCreateView.as_view(), name='create'),
    path('<int:pk>/', OrganizationDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', OrganizationUpdateView.as_view(), name='edit'),
    # path('<int:pk>/delete/',
    # views.OrganizationDeleteView.as_view(), name='delete'),

    path(
        'api/suggestions_by_inn/',
        get_org_data,
        name='api_suggestions_by_inn'
    ),
]

persons/urls.py
from django.urls import path

from . import views

app_name = 'persons'

urlpatterns = [
    path('create/', views.PersonCreateView.as_view(), name='create'),
    path('<int:pk>/edit/', views.PersonUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.PersonDeleteView.as_view(), name='delete'),
    path('', views.PersonListView.as_view(), name='list'),
]

transdoki/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='registration/login.html'),
         name='login'
         ),
    path('accounts/logout/',
         auth_views.LogoutView.as_view(next_page='login'),
         name='logout'),
    path('organizations/', include('organizations.urls')),
    path('persons/', include('persons.urls')),
    path('vehicles/', include('vehicles.urls')),
    path('trips/', include('trips.urls')),
]

trips/urls.py
from django.urls import path

from .views import TripCreateView, TripListView, TripUpdateView, print_tn

app_name = 'trips'

urlpatterns = [
    path('create/', TripCreateView.as_view(), name='create'),
    path('<int:pk>/edit/', TripUpdateView.as_view(), name='edit'),
    path('', TripListView.as_view(), name='list'),
    path('<int:pk>/print-tn/', print_tn, name='print_tn'),
]

vehicles/urls.py
from django.urls import path

from .views import VehicleCreateView, VehicleListView, VehicleUpdateView

app_name = 'vehicles'

urlpatterns = [
    path(
        'create/<int:organization_pk>/',
        VehicleCreateView.as_view(),
        name='create'
    ),
    path('<int:pk>/edit/', VehicleUpdateView.as_view(), name='edit'),
    path(
        '',
        VehicleListView.as_view(),
        name='list'
    ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}TMS{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/tables.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">

    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="nav-container">
        
        <div class="nav-left">{% if user.is_authenticated %}
            {% url 'organizations:list' as organizations_url %}
            <a href="{{ organizations_url }}" 
            class="{% if request.path == organizations_url %}active{% endif %}">Организации</a>
            
            {% url 'persons:list' as persons_url %}
            <a href="{{ persons_url }}" 
            class="{% if request.path == persons_url %}active{% endif %}">Люди</a>
            
            {% url 'vehicles:list' as vehicles_url %}
            <a href="{{ vehicles_url }}" 
            class="{% if request.path == vehicles_url %}active{% endif %}">Транспортные средства</a>
            
            {% url 'trips:list' as trips_url %}
            <a href="{{ trips_url }}" 
            class="{% if request.path == trips_url %}active{% endif %}">Поездки</a>
        {% endif %}</div>
        
        
        <div class="nav-right">
            {% if user.is_authenticated %}
                Привет, {{ user.username }}!
                <form method="post" action="{% url 'logout' %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" style="background: none; border: none; color: #007bff; cursor: pointer; text-decoration: underline;">Выйти</button>
                </form>
            {% else %}
                <a href="{% url 'login' %}">Войти</a>
                <a href="{% url 'accounts:register' %}">Регистрация</a>
            {% endif %}
        </div>
    </nav>
    
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>


</html>